### ISSUE TITLE
MigLayout V11.0 release notes

### ISSUE THREAD

**Issue by parubok** [mikaelgrev/miglayout#89]
Hi!

Where can I find release notes (or any general information) about V11.0 (Apr 24, 2021) of MigLayout?
Is it recommended for usage in production? What bugs were fixed? Features added?

Thanks,
Eli

**Comment by VestOfHolding** [comment]
There don't seem to be release notes for any releases since 4.2 in December 2011. The website haven't had their copyrights updated since 2011, and the quick start PDF since 2009.

Something about all this seems odd.

**Comment by tbee** [comment]
No worries, as with Swing itself, some software simply works and does not needs a lot of development. The occasional bug is fixed by Mikael and right now I'm trying to get 11.1 onto Maven central. It is -as they say- in maintenance. The major version is only to indicate the minimal Java version required to use MigLayout (so 11). 

Personally I use MigLayout is all my swing projects in production, a.o. a multiuser ERP system. It's my goto layout manager besides BorderLayout.

**Comment by VestOfHolding** [comment]
Nevertheless, there should still be release notes. The website appears dead, the shadow drops of what appear to be major release versions is suspect, and your comment about the major version number indicating the minimum Java version doesn't appear to be present anywhere else.

**Comment by tbee** [comment]
There is a reason why I'm switching to jreleaser. But there is always github, where you can see exactly what happened. 

Anyhow, if you are suspicious, just use something else.
